// One conversation's day, chapter by chapter. `scene` picks what the stage
// shows (see Scene.svelte); `state` is the character beside the time stamp.
// Wording follows docs/help and the app's own labels.

export const CHAPTERS = [
  {
    at: '09:00',
    state: 'ready',
    scene: 'draft',
    title: 'You describe the task',
    body: 'Open a new conversation and say what you want done, with a ticket ID if there is one. You don’t name a branch. You only pick where the work happens.',
    app: 'New branch · Branch or PR · Project folder',
  },
  {
    at: '09:00',
    state: 'starting',
    scene: 'worktree',
    title: 'It gets its own copy',
    body: 'Grove Bench makes a git worktree: a separate folder on its own branch, off main. Nothing the agent does there can touch your checkout or the other conversations.',
    app: 'A temporary branch, grove/ and the conversation’s id',
  },
  {
    at: '09:01',
    state: 'starting',
    scene: 'arrive',
    title: 'Its agent walks in',
    body: 'Every conversation has a small agent of its own. It walks up to a bench under your message, sits down and starts typing. Its skin and hair come from the conversation’s id, so it looks the same wherever it shows up.',
    app: 'Settings → The grove → Show grove characters',
  },
  {
    at: '09:02',
    state: 'working',
    scene: 'thread',
    title: 'It works where you can see it',
    body: 'The Thread tab shows what it reads, writes and runs. Its own terminal sits one tab over, opened in its worktree, so a dev server in one conversation never gets in another’s way.',
    app: 'Thread · Changes · Checkpoints · Terminal · Preview',
  },
  {
    at: '09:03',
    state: 'working',
    scene: 'rename',
    title: 'The branch names itself',
    body: 'After its first reply, the branch is renamed from your message, in the style of your project’s recent branch names. The ticket ID comes along.',
    app: 'Or set your own rule in Settings → Branches & roots',
  },
  {
    at: '09:20',
    state: 'permission',
    scene: 'permission',
    title: 'It asks before it acts',
    body: 'Each conversation has a mode that says what it may do on its own. Outside that, it waits: its character holds up an amber question mark and it counts under Needs you. Pick a mode to see what it changes.',
    app: 'Ask · Plan · Edit · Auto · Read-safe',
  },
  {
    at: '09:41',
    state: 'unread',
    scene: 'done',
    title: 'It tells you when it’s done',
    body: 'Off in another conversation? It waves in green and counts under Unread. If the Grove Bench window is in the background, you get a desktop notification too.',
    app: 'Settings → Bells → Desktop notifications',
  },
  {
    at: '09:45',
    state: 'ready',
    scene: 'changes',
    title: 'You read the diff',
    body: 'The Changes tab lists every file it touched, with the diff, unified or side by side. Revert a single file, or open it in your editor.',
    app: 'Changes tab, Alt+2',
  },
  {
    at: '10:05',
    state: 'ready',
    scene: 'checkpoints',
    title: 'Every message is a checkpoint',
    body: 'Before the agent acts on a message, Grove Bench saves a checkpoint. If a turn goes wrong, go back to it. Choose what comes back to see the difference.',
    app: 'Rewind all · Conv. only',
  },
  {
    at: '10:40',
    state: 'working',
    scene: 'others',
    title: 'Meanwhile, the others',
    body: 'You’re rarely running just one. Each conversation keeps its own branch, terminal and mode, and the sidebar shows every one of them at a glance.',
    app: 'Needs you · Working · Unread',
  },
  {
    at: '11:10',
    state: 'sleeping',
    scene: 'sleep',
    title: 'It naps when idle',
    body: 'After 30 minutes with nothing to do, its agent shuts down to save memory and CPU. The terminal keeps running. Open the conversation and it wakes on its bench, with the same mode and “always allow” choices.',
    app: 'Settings → Tending → Sleep idle conversations after',
  },
  {
    at: '14:50',
    state: 'working',
    scene: 'context',
    title: 'The grove fills up',
    body: 'Along the top of the status bar, a strip of grove grows as the conversation fills its context window: grass first, then bushes and trees. Run /compact and it thins out again.',
    app: 'Status bar · Context %',
  },
  {
    at: '16:30',
    state: 'unread',
    scene: 'ship',
    title: 'Ship it',
    body: 'When you’re happy, open a pull request from the status bar, or merge the branch your usual way.',
    app: 'Create PR',
  },
];
