/**
 * PowerShell's built-in aliases on Windows, in Windows PowerShell 5.1 and
 * PowerShell 7, keyed by alias in lower case. Taken from the "Alias" rows of
 * PowerShell's own test of its default commands, which lists each alias with
 * the editions it ships in (FullCLR is 5.1, CoreWindows is 7 on Windows):
 * https://github.com/PowerShell/PowerShell/blob/f5fd48483f678ec2f7219ba929d519f94e3e5e72/test/powershell/engine/Basic/DefaultCommands.Tests.ps1
 * and checked against BuiltInAliases in
 * https://github.com/PowerShell/PowerShell/blob/f5fd48483f678ec2f7219ba929d519f94e3e5e72/src/System.Management.Automation/engine/InitialSessionState.cs
 *
 * The two editions differ. `curl`, `wget` and `sc` are aliases only in 5.1
 * (PowerShell 6 dropped `sc` because it hid sc.exe), so in 7 they run a
 * native program of that name, if there is one. Use this table to widen
 * deny rules, never to widen allow rules.
 */
const ALIASES_BY_COMMAND: Record<string, readonly string[]> = {
  'Add-Content': ['ac'],
  'Add-PSSnapIn': ['asnp'],
  'Clear-Content': ['clc'],
  'Clear-History': ['clhy'],
  'Clear-Host': ['clear', 'cls'],
  'Clear-Item': ['cli'],
  'Clear-ItemProperty': ['clp'],
  'Clear-Variable': ['clv'],
  'Compare-Object': ['compare', 'diff'],
  'Connect-PSSession': ['cnsn'],
  'Convert-Path': ['cvpa'],
  'ConvertFrom-String': ['cfs'],
  'Copy-Item': ['copy', 'cp', 'cpi'],
  'Copy-ItemProperty': ['cpp'],
  'Disable-PSBreakpoint': ['dbp'],
  'Disconnect-PSSession': ['dnsn'],
  'Enable-PSBreakpoint': ['ebp'],
  'Enter-PSSession': ['etsn'],
  'Exit-PSSession': ['exsn'],
  'Export-Alias': ['epal'],
  'Export-Csv': ['epcsv'],
  'Export-PSSession': ['epsn'],
  'ForEach-Object': ['%', 'foreach'],
  'Format-Custom': ['fc'],
  'Format-Hex': ['fhx'],
  'Format-List': ['fl'],
  'Format-Table': ['ft'],
  'Format-Wide': ['fw'],
  'Get-Alias': ['gal'],
  'Get-ChildItem': ['dir', 'gci', 'ls'],
  'Get-CimAssociatedInstance': ['gcai'],
  'Get-CimClass': ['gcls'],
  'Get-CimInstance': ['gcim'],
  'Get-CimSession': ['gcms'],
  'Get-Clipboard': ['gcb'],
  'Get-Command': ['gcm'],
  'Get-ComputerInfo': ['gin'],
  'Get-Content': ['cat', 'gc', 'type'],
  'Get-Error': ['gerr'],
  'Get-History': ['ghy', 'h', 'history'],
  'Get-Item': ['gi'],
  'Get-ItemProperty': ['gp'],
  'Get-ItemPropertyValue': ['gpv'],
  'Get-Job': ['gjb'],
  'Get-Location': ['gl', 'pwd'],
  'Get-Member': ['gm'],
  'Get-Module': ['gmo'],
  'Get-Process': ['gps', 'ps'],
  'Get-PSBreakpoint': ['gbp'],
  'Get-PSCallStack': ['gcs'],
  'Get-PSDrive': ['gdr'],
  'Get-PSSession': ['gsn'],
  'Get-PSSnapIn': ['gsnp'],
  'Get-Service': ['gsv'],
  'Get-TimeZone': ['gtz'],
  'Get-Unique': ['gu'],
  'Get-Variable': ['gv'],
  'Get-WmiObject': ['gwmi'],
  'Group-Object': ['group'],
  'help': ['man'],
  'Import-Alias': ['ipal'],
  'Import-Csv': ['ipcsv'],
  'Import-Module': ['ipmo'],
  'Import-PSSession': ['ipsn'],
  'Invoke-CimMethod': ['icim'],
  'Invoke-Command': ['icm'],
  'Invoke-Expression': ['iex'],
  'Invoke-History': ['ihy', 'r'],
  'Invoke-Item': ['ii'],
  'Invoke-RestMethod': ['irm'],
  'Invoke-WebRequest': ['curl', 'iwr', 'wget'],
  'Invoke-WMIMethod': ['iwmi'],
  'Measure-Object': ['measure'],
  'mkdir': ['md'],
  'Move-Item': ['mi', 'move', 'mv'],
  'Move-ItemProperty': ['mp'],
  'New-Alias': ['nal'],
  'New-CimInstance': ['ncim'],
  'New-CimSession': ['ncms'],
  'New-CimSessionOption': ['ncso'],
  'New-Item': ['ni'],
  'New-Module': ['nmo'],
  'New-PSDrive': ['mount', 'ndr'],
  'New-PSSession': ['nsn'],
  'New-PSSessionConfigurationFile': ['npssc'],
  'New-PSWorkflowSession': ['nwsn'],
  'New-Variable': ['nv'],
  'Out-GridView': ['ogv'],
  'Out-Host': ['oh'],
  'Out-Printer': ['lp'],
  'Pop-Location': ['popd'],
  'powershell_ise.exe': ['ise'],
  'Push-Location': ['pushd'],
  'Receive-Job': ['rcjb'],
  'Receive-PSSession': ['rcsn'],
  'Register-CimIndicationEvent': ['rcie'],
  'Remove-CimInstance': ['rcim'],
  'Remove-CimSession': ['rcms'],
  'Remove-Item': ['del', 'erase', 'rd', 'ri', 'rm', 'rmdir'],
  'Remove-ItemProperty': ['rp'],
  'Remove-Job': ['rjb'],
  'Remove-Module': ['rmo'],
  'Remove-PSBreakpoint': ['rbp'],
  'Remove-PSDrive': ['rdr'],
  'Remove-PSSession': ['rsn'],
  'Remove-PSSnapin': ['rsnp'],
  'Remove-Variable': ['rv'],
  'Remove-WMIObject': ['rwmi'],
  'Rename-Item': ['ren', 'rni'],
  'Rename-ItemProperty': ['rnp'],
  'Resolve-Path': ['rvpa'],
  'Resume-Job': ['rujb'],
  'Select-Object': ['select'],
  'Select-String': ['sls'],
  'Set-Alias': ['sal'],
  'Set-CimInstance': ['scim'],
  'Set-Clipboard': ['scb'],
  'Set-Content': ['sc'],
  'Set-Item': ['si'],
  'Set-ItemProperty': ['sp'],
  'Set-Location': ['cd', 'chdir', 'sl'],
  'Set-PSBreakpoint': ['sbp'],
  'Set-TimeZone': ['stz'],
  'Set-Variable': ['set', 'sv'],
  'Set-WMIInstance': ['swmi'],
  'Show-Command': ['shcm'],
  'Sort-Object': ['sort'],
  'Start-Job': ['sajb'],
  'Start-Process': ['saps', 'start'],
  'Start-Service': ['sasv'],
  'Start-Sleep': ['sleep'],
  'Stop-Job': ['spjb'],
  'Stop-Process': ['kill', 'spps'],
  'Stop-Service': ['spsv'],
  'Suspend-Job': ['sujb'],
  'Tee-Object': ['tee'],
  'Trace-Command': ['trcm'],
  'Wait-Job': ['wjb'],
  'Where-Object': ['?', 'where'],
  'Write-Output': ['echo', 'write'],
};

/** Alias in lower case → the command it runs. */
export const POWERSHELL_ALIASES: ReadonlyMap<string, string> = new Map(
  Object.entries(ALIASES_BY_COMMAND).flatMap(([command, aliases]) => aliases.map((alias) => [alias, command] as const)),
);
