// A day in the life of one conversation, as its character shows it.
//
// `state` is the sidebar character. `prompt` is the character in the
// permission or question block, when there is one. `scene` is what the main
// area shows: the arrival walk, the wake-up, or the agent on its bench.
// `context` is how much of the context window is used, for the context grove.

export const BRANCH = 'feat/profile-endpoints';

export const DAY = [
  {
    at: '09:00',
    state: 'starting',
    scene: 'arrive',
    context: 0,
    row: 'Starting agent...',
    title: 'You start a conversation',
    text: 'Its agent walks up to the bench under your first message, sits down and starts typing.',
  },
  {
    at: '09:02',
    state: 'working',
    context: 9,
    row: 'Read src/routes/index.ts',
    title: 'Working',
    text: 'Blue means working. The context grove under the status bar sprouts as the conversation fills its context window.',
  },
  {
    at: '09:20',
    state: 'permission',
    prompt: 'permission',
    context: 21,
    row: 'Wants to run: npm install zod',
    title: 'Waiting for you',
    text: 'It wants to run a command. Amber means it needs you, and it counts under Needs you in the sidebar.',
  },
  {
    at: '09:23',
    state: 'working',
    prompt: 'allowed',
    context: 27,
    row: 'Write src/routes/profile.ts',
    title: 'You click Allow',
    text: 'The character in the prompt keeps a tick so you can see what you chose. The agent gets back to work.',
  },
  {
    at: '09:41',
    state: 'unread',
    context: 34,
    row: '7 tests passed. The profile endpoints are ready.',
    title: 'Finished a turn',
    text: 'You were in another conversation, so it waves in green and counts under Unread until you look.',
  },
  {
    at: '09:47',
    state: 'ready',
    context: 34,
    row: '7 tests passed. The profile endpoints are ready.',
    title: 'You open it',
    text: 'Grey and sitting: idle, ready for your next message.',
  },
  {
    at: '10:12',
    state: 'permission',
    prompt: 'asking',
    context: 41,
    row: 'Asked: which date format?',
    title: 'A question',
    text: 'You asked it to format dates. It asks which format. In the question block it waits in cyan; in the sidebar it counts under Needs you.',
  },
  {
    at: '10:15',
    state: 'working',
    prompt: 'answered',
    context: 46,
    row: 'Edit src/lib/dates.ts',
    title: 'You answer',
    text: 'The character in the question block holds a speech bubble now.',
  },
  {
    at: '10:40',
    state: 'ready',
    context: 52,
    row: 'Dates use the ISO format now.',
    title: 'Ready',
    text: 'Done for now. You head to another conversation.',
  },
  {
    at: '11:10',
    state: 'sleeping',
    context: 52,
    row: 'Dates use the ISO format now.',
    title: 'Sleeping',
    text: 'Idle for 30 minutes, the default, so its agent shut down to save memory and CPU. It stays in your list, and its terminal keeps running.',
  },
  {
    at: '13:30',
    state: 'starting',
    scene: 'wake',
    context: 52,
    row: 'Starting agent...',
    title: 'You open it after lunch',
    text: 'It wakes up on a bench, then stands and walks off while the agent starts. Click or press any key to skip.',
  },
  {
    at: '13:31',
    state: 'working',
    context: 61,
    row: 'Grep "profile" src/',
    title: 'Where it left off',
    text: 'Same conversation, same mode, same "always allow" choices.',
  },
  {
    at: '14:05',
    state: 'error',
    context: 66,
    row: 'Something went wrong',
    title: 'Error',
    text: 'Red, with an exclamation mark. The Thread tab says what happened.',
  },
  {
    at: '14:08',
    state: 'working',
    context: 78,
    row: 'Bash npm test',
    title: 'You send it again',
    text: 'Back to blue.',
  },
  {
    at: '14:50',
    state: 'working',
    context: 92,
    row: 'Edit src/routes/profile.ts',
    title: 'A full grove',
    text: '92% of the context window is used. The grove along the status bar is nearly full.',
  },
  {
    at: '14:52',
    state: 'working',
    context: 23,
    row: '/compact',
    title: 'You run /compact',
    text: 'The conversation is summarised, and the grove thins out again.',
  },
  {
    at: '15:30',
    state: 'unread',
    context: 31,
    row: 'Profile photos upload now. 11 tests passed.',
    title: 'Finished again',
    text: 'Waving in green while you are elsewhere.',
  },
  {
    at: '17:30',
    state: 'stopped',
    context: 31,
    row: 'Stopped',
    title: 'You stop it for the day',
    text: 'Its agent, background commands and terminal shut down, dev servers included. Send a message tomorrow to start it again.',
  },
];
